### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#265]
Be sure to cover subtopics of: 
- TDD
- Tests as Documentation 

Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources: 
- Engineering Practices website: https://engineering.rise8.us/general-engineering/practice-playbook/#pair-programming
- Pathway Module 5 slide 47: https://docs.google.com/presentation/d/1w8dVzbpgyeI9jwkwGgFzvfhoN7epVTnI/edit?usp=sharing&ouid=110657374635985452331&rtpof=true&sd=true
- XP Explained book

**Comment by nickeis** [comment]
https://docs.google.com/document/d/1hwHCKgifB4O3tHLSDfY1PeD5e_92ztoHSHKFN-JUDYM/edit

**Comment by bjennings-rise8** [comment]
@nickeis - Norman and I left a few comments in the doc here from our review

**Comment by nickeis** [comment]
@bjennings-rise8 @nsharpe-rise8 thanks for the feedback!  Added in the requested changes, should be good for a final review.
