### ISSUE TITLE
Continuous Integration / Continuous Deployment (CI/CD)

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#266]
Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Engineering Practices website: https://engineering.rise8.us/general-engineering/practice-playbook/#pair-programming
- Platform engineering practices website: https://engineering.rise8.us/platform-engineering/methodologies/general-best-practices/#3-continuous-integration-and-continuous-deployment-cicd
- https://tanzu.vmware.com/cicd

**Comment by MichaelMaye** [comment]
https://docs.google.com/document/d/1GnYi-Ole8u82r5S59gzGC4lVmHVXGuXDiY_t95Kx0ok/edit?usp=drive_link

**Comment by MichaelMaye** [comment]
https://docs.google.com/document/d/1GnYi-Ole8u82r5S59gzGC4lVmHVXGuXDiY_t95Kx0ok/edit?usp=drive_link

**Comment by bjennings-rise8** [comment]
@MichaelMaye I looked this over and added a couple small suggestions and then added in a little section on what a pipeline is and how it helps facilitate CI/CD

**Comment by bjennings-rise8** [comment]
@MichaelMaye - Let me know if you have the bandwidth to look over some of the comments in the g-doc here so we can resolve them and get it published!
