### ISSUE TITLE
Core Practice Content: Pairing

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#268]
Talk about pairing generally (not just pair programming) but assigning this content to engineers since engineers tend to pair the most in Rise8

Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Engineering Practices website: https://engineering.rise8.us/general-engineering/practice-playbook/#pair-programming
- XP Explained book

**Comment by nsharpe-rise8** [comment]
Link to doc: https://docs.google.com/document/d/1W5q3cqJgdbiQ-2-N9sDsj9Tp-3jQRgeyqjJqWfpGs28/edit?tab=t.0#heading=h.1b43jlogqa45
