### ISSUE TITLE
Core Practice Content: Security Early & Throughout

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#269]
Be sure to cover sub-topics:
- Establishing a Continuous Risk Management Framework (cRMF)
-  Authority to Operate (cATO)

Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Rise8 cATO playbook: https://playbook.rise8.us/
- RiseU content on cybersecurity: https://docs.google.com/document/d/1rl61Kj_t9bbcaSejlY-pq5tm6-VOV6yl5I55Ow3_DpE/edit?usp=sharing
- PE practices website: https://engineering.rise8.us/platform-engineering/methodologies/general-best-practices/#6-security

**Comment by MichaelMaye** [comment]
https://docs.google.com/document/d/16-cG8u4R7sdnCwyVbp2ERq2bPIk_oebUEYae68q9wns/edit
