### ISSUE TITLE
Core Practice Content: Making & Testing Assumptions

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#273]
Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources: 
- Assumption Content: https://docs.google.com/document/d/1pkdJoERApxOY6DnR05Jg_TsGu20f9z1Ox4UfQ1AkpPs/edit?usp=sharing
- Assumptions Workshop Play: https://delivery-playbooks.rise8.us/content/plays/design/assumptions-workshop/
- NN/g assumptions: https://www.nngroup.com/articles/tracking-questions-assumptions-facts-agile/

**Comment by bjennings-rise8** [comment]
Darla is going to work on this

**Comment by dmcgraw3654** [comment]
Ready for review: https://docs.google.com/document/d/1M9M4qkZtS5T_ekAkAbweWBpu_xvaNCB1PlZsTubbAA0/edit?pli=1&tab=t.0#heading=h.1b43jlogqa45
