### ISSUE TITLE
Core Practice Content: Data & Metrics Collection

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#274]
Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Maybe some stuff from PM playbook: https://docs.google.com/document/d/1PizJdG-7qEcefCZIO61HGbUuqXTUVpds/edit?usp=sharing&ouid=110657374635985452331&rtpof=true&sd=true
- Pathway Module 5 slide 103 covers DORA, slide 126 more generally covers metrics: https://docs.google.com/presentation/d/1w8dVzbpgyeI9jwkwGgFzvfhoN7epVTnI/edit?usp=sharing&ouid=110657374635985452331&rtpof=true&sd=true

**Comment by shubhamgoel4635** [comment]
Data and Metrics Collection Google Doc -> https://docs.google.com/document/d/1UxX2Ycg3D850y383c6cEFYPOddPxDLbzx1V2dWu-7T0/edit
