### ISSUE TITLE
Core Practice Content: Ruthless Prioritization

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#276]
Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Backlog Prioritization Play: https://delivery-playbooks.rise8.us/content/plays/product/backlog-prioritization/
- Pathway Module 4 slide 90: https://docs.google.com/presentation/d/1pzITR_e59u3nDkDeH84dbOgpBlVqCv_A/edit?usp=sharing&ouid=110657374635985452331&rtpof=true&sd=true

**Comment by aberner-va** [comment]
https://docs.google.com/document/d/1lSHQA8c9DWTnNAjxSfkvkQ3eSazmy0z0IFtPGgsMbPo/edit
