### ISSUE TITLE
Core Practice Content: Lean Startup

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#277]
Be sure to cover:
- Build Measure Learn loops => See this: https://delivery-playbooks.rise8.us/content/practices/measure-learn-iterate/
- Minimum Viable Product (MVP) Definition

Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources: 
- Lean Start Up Book (Eric Ries) 
- Measure learn iterate practice: https://delivery-playbooks.rise8.us/content/practices/measure-learn-iterate/
- MVP Def'n in DoD in Pathway Module 3 slides 118: https://docs.google.com/presentation/d/1H_G3XMQ1yqde8FujY-3BQl_N_X9tFMCB/edit?usp=sharing&ouid=110657374635985452331&rtpof=true&sd=true

**Comment by aberner-va** [comment]
https://docs.google.com/document/d/13WaKRfd5DOPauMmpiAhZ768AiP4Vb53mWRR3s4cCQZs/edit

**Comment by catrinapattonriseup** [comment]
@bjennings-rise8 @aberner-va @SagarAkre  was this just completed in the google doc and needs to be published on the site? Bec. there's a 404 error message. Can someone please confirm. Rob let me know while he was trying to review. Thanks!
