### ISSUE TITLE
Core Practice Content: Environment Control

### ISSUE THREAD

**Issue by bjennings-rise8** [rise8-us/delivery-playbooks#279]
Be sure to cover topics of:
- Containerization
- Environment parity
- Infrastructure as Code
- Configuration in the Environment

Acceptance Criteria:
Explain what the core practice is
Explain why its important
Explain it in a way that every Riser can understand it
Have a google doc that is reviewed & ready to publish
Bonus: Publish it yourself on the delivery site.

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Some info on Feature Flags around slide 60 in Pathway: https://docs.google.com/presentation/d/1w8dVzbpgyeI9jwkwGgFzvfhoN7epVTnI/edit?usp=sharing&ouid=110657374635985452331&rtpof=true&sd=true
- Platform Engineering playbook: https://engineering.rise8.us/platform-engineering/methodologies/general-best-practices/

**Comment by bjennings-rise8** [comment]
Schuyler offered to pick this one up!

**Comment by bjennings-rise8** [comment]
Renamed "Feature Flagging" to "Configuration in the Environment" as a more general practice

**Comment by derekadombek** [comment]
> Renamed "Feature Flagging" to "Configuration in the Environment" as a more general practice

I was actually kind of wondering what we meant by "Configuration in the Environment".. Because that could mean a variety of things around deploying software, for example you could have app dependencies and networking configs, that could be completely separate from feature flags. Feature Flags are a way to turn on or off(boolean) a single component after the app is already deployed in prod or any environment to help prevent the amount of bugs to the user while testing in prod. So I am def a fan of naming is back to Feature Fags or unless we don't want it to actually be about Feature Flags.

**Comment by bjennings-rise8** [comment]
I can't remember who exactly suggested including that but my assumption of what they meant was a practice of configuring things at the environment level (eg, I set an environment variable or some configuration to my database URL in the environment rather than in application code) leading to greater security and separation of concerns around what the environment controls vs what the application code has. App code reads from the environment to connect to things like services, bring in authentication keys, (possibly use feature flags) etc

Is some of that spelled out in some of the 12-factor principles? Been a min since I was an engineer but I think there may be some good stuff in the 12 factor principles we can pull from

**Comment by SagarAkre** [comment]
@nsharpe-rise8  do you have the link to the google doc for this?

**Comment by nsharpe-rise8** [comment]
@SagarAkre https://docs.google.com/document/d/1t3V3YS_dGHrvw1HQrKXf444z7vwrUY0_t4Y9B6NVgT4/edit?usp=drive_link

**Comment by SagarAkre** [comment]
Published! 
https://delivery-playbooks.rise8.us/content/practices/EnvironmentControl/
