### ISSUE TITLE
Core Practice Content: Zero-Downtime Deploys

### ISSUE THREAD

**Issue by bjennings-rise8** [rise8-us/delivery-playbooks#280]
Acceptance Criteria:
Explain what the core practice is
Explain why its important
Explain it in a way that every Riser can understand it
Have a google doc that is reviewed & ready to publish
Bonus: Publish it yourself on the delivery site.

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

**Comment by bjennings-rise8** [comment]
Brandon will take this one!

**Comment by bwood062** [comment]
https://docs.google.com/document/d/1iIgSzJr2tmVzFvz86Dd3ycIQfpjVNJeN4fk-CGvqTXo/edit#heading=h.1b43jlogqa45
