### ISSUE TITLE
Core Practice Content: Platform Health Monitoring & Observability

### ISSUE THREAD

**Issue by bjennings-rise8** [rise8-us/delivery-playbooks#281]
Acceptance Criteria:
Explain what the core practice is
Explain why its important
Explain it in a way that every Riser can understand it
Have a google doc that is reviewed & ready to publish
Bonus: Publish it yourself on the delivery site.

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Platform engineering website: https://engineering.rise8.us/platform-engineering/methodologies/general-best-practices/#4-monitoring-and-logging
- Engineering practices website: https://engineering.rise8.us/general-engineering/practice-playbook/#operating-apps

**Comment by bwood062** [comment]
https://docs.google.com/document/d/1Jo4pG1gFAIiRRPpaSFfB_t-PE_fziEh2-qdDTG54Rw0/ed

**Comment by nsharpe-rise8** [comment]
Provided review, should be good after minor adjustments!
