### ISSUE TITLE
Source Control

### ISSUE THREAD

**Issue by SagarAkre** [rise8-us/delivery-playbooks#287]
Acceptance Criteria:
- Explain what the core practice is
- Explain why its important
- Explain it in a way that every Riser can understand it
- Have a google doc that is reviewed & ready to publish
- Bonus: Publish it yourself on the delivery site. 

[Template](https://docs.google.com/document/d/1XOSrcrI819_fDYj4fO9np11GR4O2QairfFcIZHIR2go/edit)

Resources:
- Playbook page on VCS: https://delivery-playbooks.rise8.us/content/practices/version-control-systems/
- Rise8 Engineering website information GitOps: https://engineering.rise8.us/general-engineering/practice-playbook/#git-ops

**Comment by SagarAkre** [comment]
@bjennings-rise8 saw you moved this to ready to review but dont see the content? 

Last quarter anthony put some content together for version control but not sure with source control & version control are the same thing

**Comment by bjennings-rise8** [comment]
Yes! "Source Control" = "Version Control Systems"
https://delivery-playbooks.rise8.us/content/practices/version-control-systems/

Which someone wrote an article on already (Michael?) - so I was thinking we should just review it to make sure it's aligned with the new content we're writing

**Comment by bjennings-rise8** [comment]
Just going to accept what we have already! Read through it, looks good. No changes needed to actually publish it.
