### ISSUE TITLE
Eng. Play: CI/CD

### ISSUE THREAD

**Issue by catrinapattonriseup** [rise8-us/delivery-playbooks#35]
[Template](https://docs.google.com/document/d/1pStXMhW80jNuYPfyK_2n9_cDed3INa7ZBMsgU788lf4/edit?usp=drive_link)

**Comment by MichaelMaye** [comment]
https://docs.google.com/document/d/1rDbEClzFK3xycANyVOeHIfWCdqSuZsSD11HbN989FYs/

**Comment by MichaelMaye** [comment]
Moved to new RiseU Engineering folder
